#!/usr/bin/env bash

set -euo pipefail

source "installers/_functions.bash"

deploy-home() {
    _hardlink fs/home/bryan/. "$HOME"
}

deploy() {
    local dir="$1"
    _cp_sudo "fs/$dir/." "/$dir"
}

main() (
    local kernel
    kernel=$(uname -s)
    echo "Kernel: ${kernel}"

    case "$kernel" in
        "Linux")
            local dist
            dist=$(lsb_release -is)
            echo "Distribution: ${dist}"

            case "$dist" in
                "Ubuntu")
                    deploy etc
                    deploy-home
                    ;;
                "Raspbian")
                    deploy-home
                    ;;
                *)
                    echo "Operating system not supported: ${dist}"
                    exit 1
                    ;;
            esac
            ;;

        "Darwin")
            deploy-home
            ;;

        *)
            echo "Kernel not supported: ${kernel}"
            exit 1
    esac
)

if [ "$(whoami)" == "root" ]; then
    echo "this program should not be run as root."
    exit 1
fi

main
