#!/usr/bin/bash

source "installers/_functions.bash"

if ask "Install Gnome Extension Manager?"; then (
    flatpak install flathub com.mattjakeman.ExtensionManager
    # flatpak install flathub org.gnome.Extensions
) fi

# FIXME: This doesn't work (the URL is invalid without a version tag)
# if ask "Install Recommended Gnome Extensions?"; then (
#     extensions=(
#         "bluetooth-quick-connect@bjarosze.gmail.com"
#         "just-perfection-desktop@just-perfection"
#     )

#     for extension_id in "${extensions[@]}"; do
#         echo "Installing $extension_id..."
#         out="/tmp/$extension_id.zip"
#         wget -O "$out" "https://extensions.gnome.org/download-extension/$extension_id.shell-extension.zip"
#         gnome-extensions install "$out"
#         echo " Done."
#     done
# ) fi

if ask "Install Custom Gnome Extensions?"; then (
    for extension_path in gnome/extensions/*; do
        extension_id=$(basename "$extension_path")
        echo -n "Installing $extension_id..."
        gnome-extensions pack --force --out-dir="/tmp" "$extension_path" && \
        gnome-extensions install --force "/tmp/$extension_id.shell-extension.zip"
        echo " Done."
    done
) fi
