#!/usr/bin/bash

source "installers/_functions.bash"

if _shouldinstall "gnome-extension-manager" "Install Gnome Extension Manager?"; then (
    flatpak install flathub com.mattjakeman.ExtensionManager
    # flatpak install flathub org.gnome.Extensions
) fi

if _shouldinstall "recommended-gnome-extension" "Install Recommended Gnome Extensions?"; then (
    extensions=(
        "bluetooth-quick-connect@bjarosze.gmail.com"
        "just-perfection-desktop@just-perfection"
    )

    for extension_id in "${extensions[@]}"; do
        echo "Installing $extension_id..."
        out="/tmp/$extension_id.zip"
        tag=$(curl -Lfs "https://extensions.gnome.org/extension-query/?search=${i}" | jq '.extensions[0] | .shell_version_map | map(.pk) | max')

        wget -O "$out" "https://extensions.gnome.org/download-extension/${extension_id}.shell-extension.zip?version_tag=$tag"
        gnome-extensions install "$out"
        gnome-extensions enable "$extension_id"
        echo " Done."
    done
) fi

if _shouldinstall "custom-gnome-extensions" "Install Custom Gnome Extensions?"; then (
    for extension_path in gnome/extensions/*; do
        extension_id=$(basename "$extension_path")
        echo -n "Installing $extension_id..."
        gnome-extensions pack --force --out-dir="/tmp" "$extension_path" && \
        gnome-extensions install --force "/tmp/$extension_id.shell-extension.zip"
        echo " Done."
    done
) fi
