#!/usr/bin/bash

set -uo pipefail

if test "$(whoami)" = "root"; then
    echo "This program should not be run as root."
    exit 1
fi

source "installers/_functions.bash"

if _shouldinstall "ruby-install" "Install ruby-install?"; then (
    brew install ruby-install
) fi

if _shouldinstall "chruby" "Install chruby-fish?"; then (
    brew install chruby-fish
) fi

if _shouldinstall "pyenv" "Install pyenv?"; then (set -e
    # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    sudo apt install -yq \
        python3-tk \
        tk-dev \
        build-essential \
        libssl-dev \
        zlib1g-dev \
        libbz2-dev \
        libreadline-dev \
        libsqlite3-dev \
        libncursesw5-dev \
        xz-utils \
        libxml2-dev \
        libxmlsec1-dev \
        libffi-dev \
        liblzma-dev

    brew install pyenv
) fi

if _shouldinstall "nvm-fish" "Install nvm.fish? (Warning: Destructive!)"; then (set -e
    _pdir="$HOME/.config/fish/plugins"
    _sdir="$_pdir/nvm.fish"
    mkdir -p "$_pdir"
    rm -rf "$_sdir"
    git clone --depth=1 https://github.com/jorgebucaran/nvm.fish "$_sdir"
    _install_fish_plugin "nvm.fish"
    fish --login --command "emit nvm_install" # FIXME: This is supposed to install $nvm_data but doesn't

    nvm install latest
    set -U nvm_default_version latest
) fi

if _shouldinstall "nvm-sh" "Install nvm-sh?"; then (set -eo pipefail
    _latest_release=$(curl -s https://api.github.com/repos/nvm-sh/nvm/releases | jq -r ".[0].tag_name")
    PROFILE=/dev/null bash -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/${_latest_release}/install.sh | bash"
) fi

if _shouldinstall "rust" "Install rust?"; then (set -eo pipefail
    _tempfile=$(mktemp)
    curl --proto '=https' --tlsv1.2 -sSf -o "$_tempfile" https://sh.rustup.rs && \
        sh "$_tempfile" --no-modify-path
    rm "$_tempfile"
) fi
