#!/usr/bin/env bash

set -uo pipefail

if test "$(whoami)" = "root"; then
    echo "This program should not be run as root."
    exit 1
fi

source "installers/_functions.bash"

if _shouldinstall "lm-sensors" "Install lm-sensors and run sensors-detect?"; then (
    sudo apt install -yq lm-sensors
    sudo sensors-detect
) fi

if _shouldinstall "psensor" "Install psensor?"; then (
    sudo apt install -yq psensor
) fi

if _shouldinstall "bluez" "Install bluez?"; then (
    sudo apt install -yq bluez
) fi

if _shouldinstall "blueman" "Install blueman?"; then (
    sudo apt install -yq blueman
) fi

if _shouldinstall "pavucontrol" "Install pavucontrol?"; then (
    sudo apt install -yq pavucontrol
) fi

if _shouldinstall "libnss3-tools" "Install libnss3-tools (eg certutil)?"; then (
    sudo apt install -yq libnss3-tools
) fi

if _shouldinstall "postgresql" "Install & setup postgresql?"; then (set -eo pipefail
    # https://wiki.postgresql.org/wiki/Apt
    sudo apt install -yq postgresql-common
    sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
    sudo apt update -qq

    sudo apt install -yq \
        postgresql \
        postgresql-contrib \
        libpq-dev && \
    sudo apt purge postgresql-14 && \
    sudo apt purge postgresql-13

    sudo pg_conftool set port 5432
    sudo systemctl restart postgresql

    me=$(whoami)
    sudo -u postgres createuser -s "$me"
    createdb # creates database for current user
) fi

if _shouldinstall "redis" "Install redis?"; then (set -eo pipefail
    curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
    sudo apt-get update
    sudo apt-get install redis
) fi
